[package]
name = "aoc"
version = "0.1.0"
authors = ["Matthew Walton <matthew@mathw.me.uk>"]

[dependencies]
regex = "0.1"
lazy_static = "0.2.2"
itertools = "0.5.6"
rustc-serialize = "0.3"
md5 = "0.2.1"
nom = "2.0.0"
nom-test-helpers = "2.0.0"
petgraph = "0.4.2"
