use std::str::FromStr;
use crate::day18::expressions::{Expr, Factor, Term};

grammar;

pub Num: u64 = {
    r"[0-9]+" => u64::from_str(<>).unwrap()
}

pub Expr: Expr = {
    <l:Expr> "*" <r:Factor> => Expr::Multiply(Box::new(l), r),
    <Factor> => Expr::Factor(<>)
}

pub Factor: Factor = {
    <l:Factor> "+" <r:Term> => Factor::Add(Box::new(l), r),
    <Term> => Factor::Term(<>)
}

pub Term: Term = {
    <Num> => Term::Number(<>),
    "(" <Expr> ")" => Term::Expr(Box::new(<>))

}